export const API_KEY_CONNECTORS = [
  { id: 'openweather', name: 'OpenWeather', baseUrl: 'https://api.openweathermap.org/data/2.5', keyLocation: 'query', keyParam: 'appid', testPath: '/weather?q=London' },
  { id: 'newsapi', name: 'NewsAPI', baseUrl: 'https://newsapi.org/v2', keyLocation: 'header', keyParam: 'X-Api-Key', testPath: '/top-headlines?country=us' },
  { id: 'wolframalpha', name: 'Wolfram Alpha', baseUrl: 'https://api.wolframalpha.com/v2', keyLocation: 'query', keyParam: 'appid', testPath: '/result?i=population+of+france' },
  { id: 'googlemaps', name: 'Google Maps', baseUrl: 'https://maps.googleapis.com/maps/api', keyLocation: 'query', keyParam: 'key', testPath: '/geocode/json?address=paris' },
  { id: 'yelpfusion', name: 'Yelp Fusion', baseUrl: 'https://api.yelp.com/v3', keyLocation: 'header', keyParam: 'Authorization', headerPrefix: 'Bearer ', testPath: '/businesses/search?location=nyc' },
  { id: 'exchangerate', name: 'ExchangeRate API', baseUrl: 'https://v6.exchangerate-api.com/v6', keyLocation: 'path', testPath: '/latest/USD' },
  { id: 'alphavantage', name: 'Alpha Vantage', baseUrl: 'https://www.alphavantage.co/query', keyLocation: 'query', keyParam: 'apikey', testPath: '?function=SYMBOL_SEARCH&keywords=apple' },
  { id: 'nasa', name: 'NASA API', baseUrl: 'https://api.nasa.gov', keyLocation: 'query', keyParam: 'api_key', testPath: '/planetary/apod' },
  { id: 'omdb', name: 'OMDb', baseUrl: 'https://www.omdbapi.com', keyLocation: 'query', keyParam: 'apikey', testPath: '/?t=inception' },
  { id: 'unsplash', name: 'Unsplash', baseUrl: 'https://api.unsplash.com', keyLocation: 'header', keyParam: 'Authorization', headerPrefix: 'Client-ID ', testPath: '/photos/random' },
  { id: 'giphy', name: 'Giphy', baseUrl: 'https://api.giphy.com/v1', keyLocation: 'query', keyParam: 'api_key', testPath: '/gifs/trending' },
  { id: 'producthunt', name: 'Product Hunt', baseUrl: 'https://api.producthunt.com/v2/api/graphql', keyLocation: 'header', keyParam: 'Authorization', headerPrefix: 'Bearer ', testPath: '' },
  { id: 'hackernews', name: 'Hacker News', baseUrl: 'https://hacker-news.firebaseio.com/v0', keyLocation: 'none', testPath: '/topstories.json' },
  { id: 'googlebooks', name: 'Google Books', baseUrl: 'https://www.googleapis.com/books/v1', keyLocation: 'query', keyParam: 'key', testPath: '/volumes?q=dune' },
  { id: 'ipstack', name: 'IPStack', baseUrl: 'http://api.ipstack.com', keyLocation: 'query', keyParam: 'access_key', testPath: '/check' },
  { id: 'coingecko', name: 'CoinGecko', baseUrl: 'https://api.coingecko.com/api/v3', keyLocation: 'header', keyParam: 'x-cg-demo-api-key', testPath: '/ping' },
  { id: 'whois', name: 'WHOIS', baseUrl: 'https://www.whoisxmlapi.com/whoisserver/WhoisService', keyLocation: 'query', keyParam: 'apiKey', testPath: '?domainName=google.com&outputFormat=JSON' },
  { id: 'qrserver', name: 'QR Code Generator', baseUrl: 'https://api.qrserver.com/v1/create-qr-code', keyLocation: 'none', testPath: '?size=150x150&data=stoic' },
  { id: 'frankfurter', name: 'Currency Conversion', baseUrl: 'https://api.frankfurter.app', keyLocation: 'none', testPath: '/latest?from=USD&to=EUR' },
  { id: 'deepl', name: 'DeepL Translate', baseUrl: 'https://api-free.deepl.com/v2', keyLocation: 'header', keyParam: 'Authorization', headerPrefix: 'DeepL-Auth-Key ', testPath: '/usage' },
]